export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';


export const LOAD_ACCOUNTS = 'LOAD_ACCOUNTS_SUCCESS';
export const SAVE_ACCOUNTS = 'SAVE_ACCOUNTS_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOAD_CHAT_PROGRESS = 'CHAT_PROGRESS_SUCCESS';
export const SAVE_MESSAGE = 'SAVE_MESSAGE_SUCCESS';

export const LOAD_TASKS = 'TASK_SUCCESS';
export const SAVE_TASKS = 'SAVE_TASK_SUCCESS';
export const DELETE_TASK = 'DELETE_TASK_SUCCESS';


